feat(argocd client): Add handling of argocd-api-plaintext option
zapier/kubechecks pull request #274
Opened 2024-09-11 20:11 UTC by grzesuav

fixes #168

2024-09-11 20:51 UTC, Greyeye requested changes
@grzesuav can you rrun the earthy so the doc will be updated to include the new parameters?

2024-09-11 21:46 UTC, grzesuav commented
@Greyeye done, thanks for pointer

2024-09-12 01:10 UTC, djeebus approved these changes
Thanks!

2024-09-12 01:17 UTC, Greyeye approved these changes

2024-09-12 01:17 UTC, merged